__title__ = 'requests_client'
__description__ = 'Requests Client'
__url__ = 'https://github.com/dskrypa/requests_client'
__version__ = '2024.05.03'
__author__ = 'Doug Skrypa'
__author_email__ = 'dskrypa@gmail.com'
__license__ = 'Apache 2.0'
__copyright__ = 'Copyright 2024 Doug Skrypa'
